spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/notesapp
    username: postgres
    password: pwd1!pwd

logging:
  level:
    org.springframework.data.r2dbc: DEBUG

jwt:
  secret: very-very-long-secret-key-should-be-base64-encoded
  expiration: 86400 # expiration time is one day