logging:
  level:
    org.springframework.data.r2dbc: DEBUG

spring:
  flyway:
    enabled: false
    url: jdbc:postgresql://database-postgres.cc20i2ghqkcc.eu-central-1.rds.amazonaws.com:5432/notesapp
    user: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    baselineOnMigrate: true