spring:
  r2dbc:
    url: r2dbc:postgresql://database-postgres.cc20i2ghqkcc.eu-central-1.rds.amazonaws.com:5432/notesapp
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400 # expiration time is one day