server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://database-postgres.cc20i2ghqkcc.eu-central-1.rds.amazonaws.com:5432/notesapp
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  batch:
    initialize-schema: always
    job:
      enabled: false

cloud:
  aws:
    credentials:
      access-key: ${BACKET_ACCESS_KEY}
      secret-key: {BACKET_SECRET_KEY}
    region:
      static: ${BUCKET_REGION}
    stack:
      auto: false

application:
  bucket:
    name: ${BUCKET_NAME}