output:
  directoryPath: etl/src/main/resources/batchResult
  jsonFileName: notes.json
  csvFileName: notes.csv

server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/notesapp
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  batch:
    initialize-schema: always
    job:
      enabled: false
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 20MB
      max-request-size: 10MB
  main:
    allow-bean-definition-overriding: true

cloud:
  aws:
    credentials:
      access-key: accesKeyForS3Access
      secret-key: secretKeyForS3Access
    region:
      static: eu-central-1
    stack:
      auto: false

application:
  bucket:
    name: notes-etl-result