output:
  directoryPath: ./etlResult
  jsonFileName: notes.json
  csvFileName: notes.csv

server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://database-postgres.cc20i2ghqkcc.eu-central-1.rds.amazonaws.com:5432/notesapp
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  batch:
    initialize-schema: always
    job:
      enabled: false