output:
  directoryPath: ./etlResult
  jsonFileName: notes.json
  csvFileName: notes.csv

server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/notesapp
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  batch:
    initialize-schema: always
    job:
      enabled: false